
DROP DATABASE IF EXISTS platzi_operation;


CREATE DATABASE platzi_operation;

USE platzi_operation;

CREATE TABLE IF NOT EXISTS books (
book_id INTEGER (10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
author_id INTEGER(10) UNSIGNED DEFAULT NULL,
title VARCHAR(100) NOT NULL,
`year`INTEGER(11) UNSIGNED NOT NULL DEFAULT '1900',
`language` VARCHAR(2) NOT NULL DEFAULT 'es' COMMENT 'ISO 639-1 Language', 
cover_url VARCHAR(500) DEFAULT NULL,
price DOUBLE(6,2) DEFAULT NULL,
sellable TINYINT(1) NOT NULL DEFAULT '1',
`copies` INTEGER(11) NOT NULL DEFAULT '1',
`description` TEXT 
); 


CREATE TABLE IF NOT EXISTS authors (
	author_id INTEGER (10) UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	nationality VARCHAR(100) DEFAULT NULL
);

CREATE TABLE clients (

client_id INTEGER(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
`birthdate` DATE DEFAULT NULL,
gender ENUM('M','F','ND') DEFAULT 'ND',
active TINYINT(1) NOT NULL DEFAULT '1',
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP


); 


CREATE TABLE IF NOT EXISTS `transactions`(
    transaction_id INTEGER(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    book_id INTEGER(10) UNSIGNED NOT NULL,
    client_id INTEGER(10) UNSIGNED NOT NULL,
    `type` ENUM('lend','sell') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    finished TINYINT(1) NOT NULL DEFAULT '0'

);